wwwdata:
  container_name: wwwdata
  image: kreable/wwwdata
  volumes:
    - ../:/var/www
  restart: always
nginx:
  container_name: nginx
  image: kreable/nginx
  volumes:
    - ./data/config/nginx:/etc/nginx
    - ./data/log/nginx:/var/log/nginx
  links:
    - php56
    - php72
  volumes_from:
    - wwwdata
  ports:
    - "80:80"
    - "443:443"
  restart: always
php56:
  container_name: php56
  image: kreable/php56
  environment:
    PHP_ENV: 'development'
    PHP_APCU_ENABLED: 'false'
    PHP_XDEBUG_ENABLED: 'true'
    PHP_MAILCATCHER_ENABLED: 'true'
  volumes:
    - ./data/config/php/pool56/:/etc/php5/fpm/pool.d
    - ./data/config/php/ini56/development.ini:/etc/php5/mods-available/development.ini
    - ./data/config/php/ini56/production.ini:/etc/php5/mods-available/production.ini
    - ./data/log/php56:/var/log/php
  volumes_from:
    - wwwdata
  links:
    - mariadb
    - mailcatcher
    - redis
    - memcached
  restart: always
php72:
  container_name: php72
  image: fiksani/php72
  environment:
    PHP_ENV: 'development'
    PHP_XDEBUG_ENABLED: 'true'
    PHP_MAILCATCHER_ENABLED: 'true'
  volumes:
    - ./data/config/php/pool72/:/etc/php/7.2/fpm/pool.d
    - ./data/config/php/ini72/development.ini:/etc/php/7.2/mods-available/development.ini
    - ./data/config/php/ini72/production.ini:/etc/php/7.2/mods-available/production.ini
    - ./data/log/php72:/var/log/php
  volumes_from:
    - wwwdata
  links:
    - mariadb
    - mailcatcher
  restart: always
mariadb:
  container_name: mariadb
  image: kreable/mariadb
  volumes:
    - ./data/config/mariadb/my.cnf:/etc/mysql/my.cnf
    - ./data/log/mariadb:/var/log/mysql
    - ./data/mariadb:/var/lib/mysql
  environment:
    DB_ADMIN_PASS: pass
  ports:
    - "3306:3306"
  restart: always
memcached:
  container_name: memcached
  image: kreable/memcached
  ports:
    - "11211:11211"
  restart: always
mailcatcher:
  container_name: mailcatcher
  image: schickling/mailcatcher
  ports:
    - "1025:1025"
    - "1080:1080"
  restart: always
redis:
  container_name: redis
  image: redis
  volumes:
    - ./data/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
  ports:
    - "6379:6379"
  restart: always
phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  links:
    - mariadb:db
  ports:
    - "8082:80"
